Repository sstsimulator/sst-elements, pull requests merged in 2019-10, with the labels that each got.

#1377 Updating For Balar
  src/sst/elements/ariel/arielcore.cc
Labels: SST-Ariel, SST-Balar

#1383 Fixed an issue where hyperx was using total vcs instead of number of …
  src/sst/elements/merlin/topology/hyperx.cc
  src/sst/elements/merlin/topology/hyperx.h
Labels: Bug

#1385 Mjleven/fix shmem bug
  src/sst/elements/ember/test/EmberEP.py
  src/sst/elements/ember/tests/refFiles/test_EmberSweep.out
  src/sst/elements/firefly/nic.cc
  src/sst/elements/firefly/nicMsgStream.h
  src/sst/elements/firefly/nicRdmaStream.cc
  src/sst/elements/firefly/nicRdmaStream.h
  src/sst/elements/firefly/nicRecvCtx.cc
  src/sst/elements/firefly/nicShmem.h
  src/sst/elements/firefly/nicShmemStream.cc
  src/sst/elements/firefly/nicShmemStream.h
Labels: AT: RETEST

#1386 Vc init fix
  src/sst/elements/ember/tests/qos-dragonfly.sh
  src/sst/elements/ember/tests/qos-fattree.sh
  src/sst/elements/ember/tests/qos-hyperx.sh
  src/sst/elements/ember/tests/qos.load
  src/sst/elements/ember/tests/refFiles/test_qos-dragonfly.out
  src/sst/elements/ember/tests/refFiles/test_qos-fattree.out
  src/sst/elements/ember/tests/refFiles/test_qos-hyperx.out
  src/sst/elements/merlin/hr_router/hr_router.cc
Labels: Bug
